feat(assets): added 1 permission to the org role and enable 1 more api [ENG-45104]
drata/gcp-shell-drata-setup pull request #3
Opened 2024-05-01 22:54 UTC by tonygc

The following changes were added in order for GCP to get virtual assets working:

* Add `cloudasset.assets.searchAllResources` to the organizational role.
* Enable `cloudasset.googleapis.com` service.

[ENG-45104](https://drata.atlassian.net/browse/ENG-45104)

2024-05-02 06:00 UTC, AngelRocaDrata requested changes

2024-05-02 06:00 UTC, AngelRocaDrata commented on gcp-drata-script.sh
> +drata_role_name="ENG45104SHELL"
This is obviously a testing name, we just have to make sure this go back to `DrataReadOnly`

2024-05-02 17:00 UTC, tonygc commented on gcp-drata-script.sh
> +drata_role_name="ENG45104SHELL"
done https://github.com/drata/gcp-shell-drata-setup/pull/3/commits/4524375a30d23110db6f47506b47300307dc4bb7

2024-05-08 16:25 UTC, AngelRocaDrata approved these changes

2024-05-08 18:02 UTC, millennial-web approved these changes
LGTM

2024-05-29 00:41 UTC, merged